### ISSUE TITLE
Updates welcome?

### ISSUE THREAD

**Issue by dragetd** [privacyidea/docker#3]
Is there any interested in updating this docker image and getting it into a more usable state? I wanted to ask before creating a PR :-)

**Comment by plettich** [comment]
Hi,
well, we do welcome PRs but maybe this repo needs a complete overhaul since it is quite old.
We can certainly discuss this in a PR, thank You.

**Comment by brunocascio** [comment]
Any updates here? I glad to contribute here.

**Comment by plettich** [comment]
Closing in favor of #6
